/*
 * Copyright (c) 2017 Christian Taedcke
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief Board configuration macros for the SiM3U soc
 *
 */

#ifndef SOC_H_
#define SOC_H_

#include <sys/util.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef _ASMLANGUAGE

#include "SIM3U167_B.h"

#endif /* !_ASMLANGUAGE */

#ifdef CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0
#define SIM3U_CROSSBAR_0_PB0_SKIPPED_MASK                                                          \
	(BIT(0) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_0_SKIP) |                      \
	 BIT(1) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_1_SKIP) |                      \
	 BIT(2) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_2_SKIP) |                      \
	 BIT(3) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_3_SKIP) |                      \
	 BIT(4) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_4_SKIP) |                      \
	 BIT(5) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_5_SKIP) |                      \
	 BIT(6) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_6_SKIP) |                      \
	 BIT(7) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_7_SKIP) |                      \
	 BIT(8) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_8_SKIP) |                      \
	 BIT(9) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_9_SKIP) |                      \
	 BIT(10) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_10_SKIP) |                    \
	 BIT(11) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_11_SKIP) |                    \
	 BIT(12) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_12_SKIP) |                    \
	 BIT(13) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_13_SKIP) |                    \
	 BIT(14) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_14_SKIP) |                    \
	 BIT(15) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB0_15_SKIP))

#define SIM3U_CROSSBAR_0_PB1_SKIPPED_MASK                                                          \
	(BIT(0) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_0_SKIP) |                      \
	 BIT(1) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_1_SKIP) |                      \
	 BIT(2) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_2_SKIP) |                      \
	 BIT(3) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_3_SKIP) |                      \
	 BIT(4) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_4_SKIP) |                      \
	 BIT(5) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_5_SKIP) |                      \
	 BIT(6) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_6_SKIP) |                      \
	 BIT(7) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_7_SKIP) |                      \
	 BIT(8) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_8_SKIP) |                      \
	 BIT(9) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_9_SKIP) |                      \
	 BIT(10) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_10_SKIP) |                    \
	 BIT(11) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_11_SKIP) |                    \
	 BIT(12) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_12_SKIP) |                    \
	 BIT(13) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_13_SKIP) |                    \
	 BIT(14) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_14_SKIP) |                    \
	 BIT(15) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0_PB1_15_SKIP))
#endif /* CONFIG_SOC_SERIES_SIM3U_CROSSBAR_0 */

#ifdef CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1
#define SIM3U_CROSSBAR_1_PB2_SKIPPED_MASK                                                          \
	(BIT(0) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_0_SKIP) |                      \
	 BIT(1) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_1_SKIP) |                      \
	 BIT(2) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_2_SKIP) |                      \
	 BIT(3) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_3_SKIP) |                      \
	 BIT(4) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_4_SKIP) |                      \
	 BIT(5) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_5_SKIP) |                      \
	 BIT(6) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_6_SKIP) |                      \
	 BIT(7) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_7_SKIP) |                      \
	 BIT(8) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_8_SKIP) |                      \
	 BIT(9) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_9_SKIP) |                      \
	 BIT(10) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_10_SKIP) |                    \
	 BIT(11) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_11_SKIP) |                    \
	 BIT(12) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_12_SKIP) |                    \
	 BIT(13) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_13_SKIP) |                    \
	 BIT(14) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_14_SKIP) |                    \
	 BIT(15) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB2_15_SKIP))

#define SIM3U_CROSSBAR_1_PB3_SKIPPED_MASK                                                          \
	(BIT(0) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_0_SKIP) |                      \
	 BIT(1) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_1_SKIP) |                      \
	 BIT(2) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_2_SKIP) |                      \
	 BIT(3) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_3_SKIP) |                      \
	 BIT(4) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_4_SKIP) |                      \
	 BIT(5) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_5_SKIP) |                      \
	 BIT(6) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_6_SKIP) |                      \
	 BIT(7) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_7_SKIP) |                      \
	 BIT(8) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_8_SKIP) |                      \
	 BIT(9) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_9_SKIP) |                      \
	 BIT(10) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_10_SKIP) |                    \
	 BIT(11) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_11_SKIP) |                    \
	 BIT(12) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_12_SKIP) |                    \
	 BIT(13) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_13_SKIP) |                    \
	 BIT(14) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_14_SKIP) |                    \
	 BIT(15) * IS_ENABLED(CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1_PB3_15_SKIP))
#endif /* CONFIG_SOC_SERIES_SIM3U_CROSSBAR_1 */

#ifdef __cplusplus
}
#endif

#endif /* SOC_H_ */
